context:
  version: "0.9.2"

package:
  name: go-grip
  version: ${{ version }}

source:
  url: https://github.com/chrishrb/go-grip/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 3c628505f277dca44fc78e46159b1c79561712560bd89b4a3d57f44e5d5e9e94

build:
  number: 0
  script:
    - go-licenses save . --save_path library_licenses
    - if: unix
      then: go build -v -o $PREFIX/bin/go-grip -ldflags="-s -w"
      else: go build -v -o %LIBRARY_BIN%\go-grip.exe -ldflags="-s"

requirements:
  build:
    - ${{ compiler("go-nocgo") }}
    - go-licenses

tests:
  - script: go-grip --help
  - package_contents:
      bin:
        - go-grip
      strict: true

about:
  homepage: https://github.com/chrishrb/go-grip
  summary: Preview Markdown files locally before committing them.
  description: |
    go-grip is a lightweight, Go-based tool designed to render Markdown files locally, replicating GitHub's style.
  license: MIT
  license_file:
    - LICENSE
    - library_licenses/
  documentation: https://pkg.go.dev/github.com/chrishrb/go-grip
  repository: https://github.com/chrishrb/go-grip

extra:
  recipe-maintainers:
    - imagejan
